# k8s-db/00-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: swift-order
type: Opaque
stringData:
  # Use a more secure password in a real environment!
  POSTGRES_PASSWORD: "admin123"